# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe708e5676f531deb66d3a0154ee5365c16ebf47189fa87c3d81a822438508187c7289a00e3e661a87e592c2497396fe50ef204654a641ad17d33d396da77388

test:
  secret_key_base: 156c2d3a25b5597f431ef7fb5d9dc80e87fac7480369d51a81f6f2547459b0be1f3fbbe26e737bb21d11c1eaf38b9c448251f530011ad6fde3a2b2498d8b39c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
